"use client"
import React, { useState, useEffect } from "react";
import NavBar from "./public/navbar";
import MessageBar from "./public/messageBar";
import LeftSidebar from "./components/sidebar/leftSidebar";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="bg-gray-100 min-h-screen">
          {/* Fixed navbar */}
          <div className="fixed w-full z-50">
            <NavBar />
          </div>
          
          {/* Main layout */}
          <div className="pt-16 flex flex-col md:flex-row">
            {/* Left sidebar */}
            <LeftSidebar />
            
            {/* Main content area - will be filled by page components */}
            <div className="flex-1 flex justify-center">
              <main className="w-full sm:max-w-xl md:max-w-2xl lg:max-w-4xl px-4 py-6">
                {children}
              </main>
            </div>
            
            {/* Right sidebar (MessageBar) */}
            <MessageBar />
          </div>
        </div>
      </body>
    </html>
  );
}
