name: Run tests

# Event trigger when having a pull request
on:
  pull_request:
    branches: ['main']

# One job: test
jobs:
  tests:
    runs-on: ubuntu-latest
    # Run every ci/cd on frontend folder
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm test