name: Run tests

on:
  pull_request:
    branches: ['master']

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Change directory
        run: cd frontend/

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm test